k3s installer

diff --git a/raspberry_pi/install_docker b/raspberry_pi/install_docker
--- a/raspberry_pi/install_docker
+++ b/raspberry_pi/install_docker
@@ -1,42 +1,40 @@
 #!/bin/bash
+set -e
 
-source $HOME/development/bash_scripts/shared/indent
+failed? () {
+    if [$1 -ne 0]; then
+        echo "Docker failed to installed! (error: $1)"
+        exit $2
+    fi
+}
 
-DOCKER_USER=$USER
-OTHER_ARGUMENTS=( )
+echo "Instaling Docker..."
 
-# Loop through arguments and process them
-for arg in "$@"
-do
-    case $arg in
-        -u=*|--docker-user=*)
-        DOCKER_USER="${arg#*=}"
-        shift
-        ;;
-        -u|--docker-user)
-        DOCKER_USER="$2"
-        shift # Remove argument name from processing
-        shift # Remove argument value from processing
-        ;;
-        *)
-        OTHER_ARGUMENTS+=("$1")
-        shift # Remove generic argument from processing
-        ;;
-    esac
-done
+echo "Removing older versions..."
+sudo apt-get remove docker \
+  docker-engine \
+  docker.io \ 
+  containerd runc
+failed? $? 1
 
-echo  "Instaling Docker with $DOCKER_USER as user"
+sudo apt-get update
+failed? $? 2
 
-echo "Downloading Docker intallation script" | indent 
-curl -fsSL https://get.docker.com -o get-docker.sh | indent 2
+echo "Adding Docker’s official GPG key..."
+curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+failed? $? 3
 
-echo "Running Docker intallation script" | indent 
-sh get-docker.sh | indent 2
+echo "Adding Docker’s stable repository..."
+echo \ 
+  "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \ 
+  | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+failed? $? 4
 
-echo "Removing Docker intallation script" | indent 
-rm get-docker.sh | indent 2
+sudo apt-get update
+failed? $? 5
 
-echo "Adding $DOCKER_USER to docker group" | indent 
-sudo usermod -aG docker $DOCKER_USER | indent 2
+echo "Installing packages..."
+sudo apt-get install docker-ce docker-ce-cli containerd.io -y
+failed? $? 6
 
 echo "Docker Installed!"
